#!/usr/bin/python3.5


import pandas as pd
import numpy as np

import sys

import matplotlib.pyplot as plt
from parseRunFiles import RunFileParser

# Extracts and returns actual inital particle source angles
from fncs.fnc_findSourceAngle import findSourceAngle

detector_hits = pd.read_csv('./data/hits.csv',
                           names=["det","x", "y", "z","energy", "code"],
                           dtype={"det": np.int32, "x":np.float64,
                           "y": np.float64, "z":np.float64,
                           "code": np.unicode_},
                           delimiter=',',
                           skiprows=1,
                           skipfooter=1,
                           engine='python')


detectorDoubleHits = detector_hits.index[detector_hits["code"] == "DH"].tolist()

whichDetectorIndex = detector_hits.index[detector_hits["code"] == "GH"].tolist()

[det, X, Z]  = [detector_hits['det'][whichDetectorIndex],
               detector_hits['x'][whichDetectorIndex],
               detector_hits['z'][whichDetectorIndex]]


deltaX = np.array([])
deltaZ = np.array([])

gap = 0.5 # cm

for count, el in enumerate(det):

    # pandas series can throw a KeyError if character starts line
    # TODO: replace this with parse command that doesn't import keyerror throwing lines
    while True:
        try:
            pos1 = det[count]
            pos2 = det[count+1]

            X[count]
            Z[count]

            X[count+1]
            Z[count+1]
        except:
            count = count + 1
            if count == len(det):
                break
            continue
        break

    # Checks if first hit detector == 1 and second hit detector == 2
    if np.equal(pos1, 1) & np.equal(pos2, 2):
        deltaX = np.append(deltaX, X[count] - X[count+1])
        deltaZ = np.append(deltaZ, Z[count] - Z[count+1])

        # Successful pair, continues to next possible pair
        count = count + 2
    else:
        # Unsuccessful pair, continues
        count = count + 1


theta = np.arctan2(deltaZ, gap) * 180 / np.pi
phi = np.arctan2(deltaX, gap) * 180 / np.pi

rfp = RunFileParser('run_1_angle.mac')


plt.figure()
plt.subplots_adjust(left=0.09, bottom=0.10, right=0.96, top=0.98,
                wspace=0.20, hspace=0.30)

plt.subplot(2,1,1)
plt.hist(theta, bins=100, density=True)
plt.axvline(x=np.median(theta), color='r', linestyle='--')
plt.axvline(x=np.mean(theta), color='g', linestyle='--')
plt.xlabel('Theta Angle (degrees)')

plt.subplot(2,1,2)
plt.hist(phi, bins=100, density=True)
plt.axvline(x=np.median(phi), color='r', linestyle='--')
plt.axvline(x=np.mean(phi), color='g', linestyle='--')
plt.xlabel('Phi Angle (degrees)')

try:
    stat = sys.argv[1]
except IndexError:
    # else if no argument passed to program, defaults to mean
    stat = 'mean'

# Determines what statistic is used to estimate the maximum likelihood point
if stat == 'median':
    phi_est = np.median(phi)
    theta_est = np.median(theta)
elif stat == 'mean':
    phi_est = np.mean(phi)
    theta_est = np.mean(theta)

theta_actual, phi_actual, numberOfParticles = findSourceAngle()

theta_error = round(theta_est - theta_actual, 4)
phi_error = round(phi_est - phi_actual, 4)

print("-------------------------------------------------------------")
print("Angle Estimation: \n")
# divide 6 comes from 6 parameters recorded per particle
print("Energy = " + str(rfp.getEnergy()))
print("Percentage of double hits = " + str(round(len(detectorDoubleHits)/len(det)*100, 3)) + '%')
print("Number of particles: " + str(numberOfParticles))
print("Actual [degrees]: theta=" + str(theta_actual) + ", phi=" +  str(phi_actual))
print("Experimental [degrees]: theta=" + str(theta_est) + ", phi=" +  str(phi_est))
print("(Theta, Phi) absolute error [degrees]: (" + str(theta_error) + ", " + str(phi_error) + ")")
print("-------------------------------------------------------------\n")



plt.show()
